### ISSUE TITLE
Add FOSS History slides

### ISSUE THREAD

**Issue by justwheel** [deejoe/presentations#3]
I'd be interested in seeing the full copy of your slides from 2019-10-11 RITlug meeting on FOSS History. :slightly_smiling_face:

https://ritlug.com/announcements/2019/10/11/w07-foss-history/

**Comment by deejoe** [comment]
Fixed in https://github.com/deejoe/presentations/commit/809439f98c4bf2d2e77e9ec82db4ffb50b94292d

**Comment by deejoe** [comment]
Sorry, https://github.com/deejoe/presentations/commit/eb9272732d60688c94896ce6ef1da5ffb0d8d7b5 brings this up to what I presented, more or less.

**Comment by justwheel** [comment]
Awesome. Thanks @deejoe!
